"use client";

import * as DialogPrimitive from "@radix-ui/react-dialog";
import { LoaderCircle, Pencil, X } from "lucide-react";
import { useRef, useState, useTransition } from "react";
import { toast } from "sonner";
import { addExceptionAction, changePasswordAction, deleteExceptionAction, sendTestEmailAction, updateExceptionAction, updateNotificationAction, updateScheduleAction } from "@/app/actions";
import { ActionButton, ManagedForm, SubmitButton } from "@/components/managed-form";
import { ConfirmAction } from "@/components/ui/alert-dialog";
import { Button } from "@/components/ui/button";
import { Select } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { EMAIL_TEMPLATE_VARIABLES, renderEmailTemplate } from "@/domain/notifications/email-template";

type ExceptionItem = { id: string; date: string; reason: string };
type Props = {
  settings: { monday:boolean;tuesday:boolean;wednesday:boolean;thursday:boolean;friday:boolean;saturday:boolean;sunday:boolean;emailEnabled:boolean;notificationMode:string;notificationTime:string;timezone:string;dayBeforeSubjectTemplate:string;dayBeforeBodyTemplate:string;sameDaySubjectTemplate:string;sameDayBodyTemplate:string };
  exceptions: ExceptionItem[];
  system: { healthy:boolean; database:string; workerVersion:string; lastTick:string; lastScheduler:string; lastNotification:string; lastError:string | null; smtpConfigured:boolean };
};

const previewVariables = { recipient_name:"王小雨", partner_name:"陈明", duty_date:"2026-09-05", member_1_name:"王小雨", member_2_name:"陈明" };

function TemplateEditor({ subjectName, bodyName, defaultSubject, defaultBody }: { subjectName:string;bodyName:string;defaultSubject:string;defaultBody:string }) {
  const [subject, setSubject] = useState(defaultSubject);
  const [body, setBody] = useState(defaultBody);
  const [target, setTarget] = useState<"subject" | "body">("body");
  const subjectRef = useRef<HTMLInputElement>(null);
  const bodyRef = useRef<HTMLTextAreaElement>(null);
  let preview: ReturnType<typeof renderEmailTemplate> | null = null;
  let previewError = "";
  try { preview = renderEmailTemplate(subject, body, previewVariables); } catch (error) { previewError = error instanceof Error ? error.message : "模板无法预览"; }
  const insertVariable = (key: string) => {
    const value = `{{${key}}}`;
    const field = target === "subject" ? subjectRef.current : bodyRef.current;
    const current = target === "subject" ? subject : body;
    const start = field?.selectionStart ?? current.length;
    const end = field?.selectionEnd ?? start;
    const next = `${current.slice(0, start)}${value}${current.slice(end)}`;
    if (target === "subject") setSubject(next); else setBody(next);
    requestAnimationFrame(() => { field?.focus(); field?.setSelectionRange(start + value.length, start + value.length); });
  };
  return <div className="template-layout"><div className="grid"><div className="field"><label htmlFor={subjectName}>邮件主题</label><input ref={subjectRef} id={subjectName} className="input" name={subjectName} value={subject} onChange={(event) => setSubject(event.target.value)} onFocus={() => setTarget("subject")} maxLength={160} required /></div><div className="field"><label htmlFor={bodyName}>邮件正文</label><textarea ref={bodyRef} id={bodyName} className="input textarea" name={bodyName} value={body} onChange={(event) => setBody(event.target.value)} onFocus={() => setTarget("body")} maxLength={10000} rows={10} required /></div><div><div className="setting-label">可用变量</div><div className="setting-help">先把光标放到主题或正文，再点变量插入。发送时会替换成真实数据。</div><div className="template-variables" role="group" aria-label="可用模板变量">{EMAIL_TEMPLATE_VARIABLES.map((item) => <button className="template-variable" type="button" key={item.key} onClick={() => insertVariable(item.key)} title={`插入${item.label}`}>{`{{${item.key}}}`}<span>{item.label}</span></button>)}</div></div></div><div className="template-preview" aria-live="polite"><div className="template-preview-label">预览</div>{preview ? <><div className="template-preview-subject">{preview.subject}</div><div className="template-preview-body">{preview.text}</div></> : <div className="template-preview-error">{previewError}</div>}</div></div>;
}

function EditException({ item }: { item: ExceptionItem }) {
  const [open, setOpen] = useState(false); const [pending, startTransition] = useTransition();
  return <DialogPrimitive.Root open={open} onOpenChange={setOpen}><DialogPrimitive.Trigger asChild><Button variant="ghost" size="sm"><Pencil size={14} />编辑</Button></DialogPrimitive.Trigger><DialogPrimitive.Portal><DialogPrimitive.Overlay className="dialog-overlay" /><DialogPrimitive.Content className="dialog-content"><DialogPrimitive.Title className="dialog-title">编辑跳过日期</DialogPrimitive.Title><DialogPrimitive.Description className="dialog-description">保存后，尚未发送通知的下一次排班会自动校正。</DialogPrimitive.Description><form className="grid" action={(data) => startTransition(async () => { try { const result = await updateExceptionAction(data); if (result.ok) { toast.success(result.message); setOpen(false); } else toast.error(result.message); } catch { toast.error("连接中断，请稍后重试"); } })}><input type="hidden" name="id" value={item.id} /><div className="field"><label htmlFor={`exception-date-${item.id}`}>日期</label><input id={`exception-date-${item.id}`} className="input" type="date" name="date" defaultValue={item.date} required /></div><div className="field"><label htmlFor={`exception-reason-${item.id}`}>原因</label><input id={`exception-reason-${item.id}`} className="input" name="reason" defaultValue={item.reason} required maxLength={120} /></div><div className="dialog-actions"><DialogPrimitive.Close asChild><Button disabled={pending}>取消</Button></DialogPrimitive.Close><Button variant="primary" type="submit" disabled={pending}>{pending && <LoaderCircle className="spin" size={15} />}{pending ? "正在保存…" : "保存"}</Button></div></form><DialogPrimitive.Close asChild><Button className="dialog-close" variant="ghost" size="icon" aria-label="关闭"><X size={17} /></Button></DialogPrimitive.Close></DialogPrimitive.Content></DialogPrimitive.Portal></DialogPrimitive.Root>;
}

export function SettingsPanel({ settings, exceptions, system }: Props) {
  const days = [["monday", "周一"], ["tuesday", "周二"], ["wednesday", "周三"], ["thursday", "周四"], ["friday", "周五"], ["saturday", "周六"], ["sunday", "周日"]] as const;
  return <Tabs defaultValue="schedule"><TabsList><TabsTrigger value="schedule">排班</TabsTrigger><TabsTrigger value="exceptions">跳过日期</TabsTrigger><TabsTrigger value="notifications">通知</TabsTrigger><TabsTrigger value="system">系统</TabsTrigger><TabsTrigger value="account">账号</TabsTrigger></TabsList>
    <TabsContent value="schedule"><section className="card"><div className="card-head"><h2>值日星期</h2></div><div className="card-body"><ManagedForm action={updateScheduleAction}><div>{days.map(([key, label]) => <div className="setting-row" key={key}><div><div className="setting-label">{label}</div><div className="setting-help">{settings[key] ? "当天安排值日" : "当天跳过"}</div></div><Switch name={key} defaultChecked={settings[key]} aria-label={`${label}安排值日`} /></div>)}</div><div className="actions" style={{ marginTop: 20 }}><SubmitButton variant="primary">保存</SubmitButton></div></ManagedForm></div></section></TabsContent>
    <TabsContent value="exceptions"><section className="card"><div className="card-head"><h2>跳过日期</h2></div><div className="card-body"><ManagedForm action={addExceptionAction} resetOnSuccess className="form-grid"><div className="field"><label htmlFor="exception-date">日期</label><input id="exception-date" className="input" type="date" name="date" required /></div><div className="field"><label htmlFor="exception-reason">原因</label><div className="actions"><input id="exception-reason" className="input" name="reason" placeholder="例如：公司放假" required maxLength={120} style={{ flex: 1 }} /><SubmitButton variant="primary">添加</SubmitButton></div></div></ManagedForm><div style={{ marginTop: 24 }}><ul className="list">{exceptions.map((item) => <li className="list-row" key={item.id}><div><strong>{item.date}</strong><div className="muted small">{item.reason}</div></div><div className="actions"><EditException item={item} /><ConfirmAction title="删除这个跳过日期？" description={`${item.date} 将恢复按星期规则排班。`} triggerLabel="删除" confirmLabel="确认删除" action={deleteExceptionAction} hiddenFields={{ id: item.id }} /></div></li>)}{exceptions.length === 0 && <li className="empty-state"><div><strong>没有跳过日期</strong><span>固定休息日请在“排班”中设置。</span></div></li>}</ul></div></div></section></TabsContent>
    <TabsContent value="notifications"><section className="card"><div className="card-head"><h2>邮件通知</h2><span className={`pill ${system.smtpConfigured ? "good" : "off"}`}>{system.smtpConfigured ? "SMTP 已配置" : "SMTP 未配置"}</span></div><div className="card-body"><ManagedForm action={updateNotificationAction} className="grid"><div className="setting-row"><div><div className="setting-label">发送邮件提醒</div><div className="setting-help">关闭后不会创建新的邮件任务。</div></div><Switch name="emailEnabled" defaultChecked={settings.emailEnabled} aria-label="发送邮件提醒" /></div><div className="form-grid"><div className="field"><label>提醒时间</label><input className="input" type="time" name="notificationTime" defaultValue={settings.notificationTime} required /></div><div className="field"><label>提醒方式</label><Select name="notificationMode" defaultValue={settings.notificationMode} ariaLabel="提醒方式" options={[{ value:"day_before", label:"前一天" }, { value:"same_day", label:"当天" }, { value:"both", label:"前一天和当天" }]} /></div></div><div className="field"><label htmlFor="timezone">时区</label><input id="timezone" className="input" name="timezone" defaultValue={settings.timezone} required spellCheck={false} /></div><div className="settings-divider" /><div><div className="setting-label">邮件内容</div><div className="setting-help">分别设置两种提醒。测试邮件使用当前已保存的“前一天”模板。</div></div><Tabs defaultValue="day-before" className="template-tabs"><TabsList><TabsTrigger value="day-before">前一天提醒</TabsTrigger><TabsTrigger value="same-day">当天提醒</TabsTrigger></TabsList><TabsContent value="day-before" forceMount><TemplateEditor subjectName="dayBeforeSubjectTemplate" bodyName="dayBeforeBodyTemplate" defaultSubject={settings.dayBeforeSubjectTemplate} defaultBody={settings.dayBeforeBodyTemplate} /></TabsContent><TabsContent value="same-day" forceMount><TemplateEditor subjectName="sameDaySubjectTemplate" bodyName="sameDayBodyTemplate" defaultSubject={settings.sameDaySubjectTemplate} defaultBody={settings.sameDayBodyTemplate} /></TabsContent></Tabs><div className="actions"><SubmitButton variant="primary">保存通知设置</SubmitButton><ActionButton type="button" action={sendTestEmailAction}>发送已保存模板的测试邮件</ActionButton></div></ManagedForm></div></section></TabsContent>
    <TabsContent value="system"><section className="card"><div className="card-head"><h2>运行状态</h2><span className={`pill ${system.healthy ? "good" : "off"}`}>{system.healthy ? "正常" : "需要检查"}</span></div><div className="card-body"><ul className="list"><li className="list-row"><span>数据库</span><span className="pill good">{system.database}</span></li><li className="list-row"><span>Worker 版本</span><span>{system.workerVersion}</span></li><li className="list-row"><span>最近心跳</span><span>{system.lastTick}</span></li><li className="list-row"><span>最近生成排班</span><span>{system.lastScheduler}</span></li><li className="list-row"><span>最近检查通知</span><span>{system.lastNotification}</span></li>{system.lastError && <li className="notice" role="alert">{system.lastError}</li>}</ul></div></section></TabsContent>
    <TabsContent value="account"><section className="card"><div className="card-head"><h2>修改密码</h2></div><div className="card-body"><ManagedForm action={changePasswordAction} className="grid" style={{ maxWidth: 520 }}><div className="field"><label htmlFor="current-password">当前密码</label><input id="current-password" className="input" type="password" name="currentPassword" autoComplete="current-password" required /></div><div className="field"><label htmlFor="new-password">新密码</label><input id="new-password" className="input" type="password" name="newPassword" autoComplete="new-password" minLength={12} maxLength={128} required /><div className="setting-help">至少 12 个字符</div></div><div className="field"><label htmlFor="confirm-password">确认新密码</label><input id="confirm-password" className="input" type="password" name="confirmPassword" autoComplete="new-password" minLength={12} maxLength={128} required /></div><div><SubmitButton variant="primary">修改密码</SubmitButton></div></ManagedForm></div></section></TabsContent>
  </Tabs>;
}
